version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    networks:
      - Bookstore
    ports:
      - 5432:5432
    volumes:
      - postgres:/data/postgres

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.ru
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - 5050:5050
    networks:
      - Bookstore
    volumes:
      - pgadmin:/var/lib/pgadmin

  mongo:
    image: mongo
    restart: unless-stopped
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: changeme
    networks:
      - Bookstore
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: changeme
      ME_CONFIG_MONGODB_URL: mongodb://root:changeme@mongo:27017/
    networks:
      - Bookstore

  pulsar:
    image: apachepulsar/pulsar:latest
    container_name: broker
    restart: unless-stopped
    ports:
      - 8080:8080
      - 6650:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    networks:
      - Bookstore
    command: bin/pulsar standalone

  # dashboard:
  #   image: apachepulsar/pulsar-manager:latest
  #   restart: unless-stopped
  #   container_name: broker-dashboard
  #   ports:
  #     - "9527:9527"
  #     - "7750:7750"
  #   depends_on:
  #     - pulsar
  #   links:
  #     - pulsar
  #   environment:
  #     SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
  #   networks:
  #     - Bookstore

networks:
  Bookstore:
    name: Bookstore

volumes:
  postgres:
  mongo:
  pgadmin:
  mongo-express:
    driver: local
